version: '3.7'
services: 
    react-cra:
        container_name: react-cra
        command: "npm start"
        image: vcygni/react-dev:cra
        build:
            context: ./
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=development
        volumes: 
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - react-dev
networks: 
    react-dev:
        name: react-dev
        driver: bridge